"""The WP-09 Zone Index fixture (design §2): z_synthetic_002 + index/ in tools/tests/fixtures/zones and in
Content/Golmok/Zones, generated by tools/scripts/make_index_fixture.py.

- write_all() regenerates exactly the committed bytes in both copies (and --check agrees)
- the index validates against the spec schema and its four cell files are the design §2 cell table
- z_synthetic_002 sits 200 m east of z_synthetic_001, in the next z16 cell column, without footprint overlap
- `golmok-zone index build --strict` over the fixture zones root (which holds index/) reproduces the index
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import numpy as np
import pytest
from shapely.geometry import Polygon

from golmok_tools.zone import index as zi
from golmok_tools.zone import manifest as zm
from golmok_tools.zone import schema, transform
from golmok_tools.zone.cli import main as zone_main

REPO = Path(__file__).resolve().parents[2]
SCRIPTS = REPO / "tools" / "scripts"
FIXTURE_ZONES = REPO / "tools" / "tests" / "fixtures" / "zones"
CONTENT_ZONES = REPO / "unreal" / "Golmok" / "Content" / "Golmok" / "Zones"
ZONE_001 = "z_synthetic_001"
ZONE_001_IN = "z_synthetic_001_interior"
ZONE_002 = "z_synthetic_002"
IDS = [ZONE_001, ZONE_001_IN, ZONE_002]
# design §2 "픽스처 셀 표": cell file -> zones in winning order (priority desc, version desc, id)
EXPECTED_CELLS = {
    "16_55873_25379.json": [ZONE_001_IN, ZONE_001],
    "16_55873_25380.json": [ZONE_001],
    "16_55874_25379.json": [ZONE_001_IN, ZONE_001, ZONE_002],
    "16_55874_25380.json": [ZONE_001, ZONE_002],
}
OUTPUT_DIRS = (
    Path("tools/tests/fixtures/zones") / ZONE_002,
    Path("unreal/Golmok/Content/Golmok/Zones") / ZONE_002,
    Path("tools/tests/fixtures/zones/index"),
    Path("unreal/Golmok/Content/Golmok/Zones/index"),
)


def _tree(folder: Path) -> dict[str, bytes]:
    """{normpath relative path: bytes} of every file under folder (sorted rglob, CRLF folded)."""
    out = {}
    for p in sorted(folder.rglob("*")):
        if p.is_file():
            out[os.path.normpath(str(p.relative_to(folder)))] = p.read_bytes().replace(b"\r\n", b"\n")
    return out


def _read(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _origin(zone_id: str) -> tuple[float, float, float]:
    o = _read(FIXTURE_ZONES / zone_id / "v1" / zm.MANIFEST_NAME)["origin"]
    return o["lat"], o["lon"], o["height_ellipsoidal"]


def _footprint(zone_id: str) -> Polygon:
    return zm.footprint_polygon(_read(FIXTURE_ZONES / zone_id / "v1" / zm.MANIFEST_NAME)["footprint_wgs84"])


def test_generator_reproduces_committed_index_and_zone_002(tmp_path):
    pytest.importorskip("scipy")
    pytest.importorskip("fast_simplification")
    sys.path.insert(0, str(SCRIPTS))
    try:
        import make_index_fixture as mif
    finally:
        sys.path.remove(str(SCRIPTS))
    for rel in OUTPUT_DIRS:
        assert (REPO / rel).is_dir(), f"run python tools/scripts/make_index_fixture.py ({rel})"
    written = mif.write_all(tmp_path)
    assert written and all(p.is_file() for p in written)
    for rel in OUTPUT_DIRS:
        assert _tree(tmp_path / rel) == _tree(REPO / rel), rel
    # the two committed copies are byte-identical, and only manifest + blockers of z_synthetic_002 exist
    assert _tree(REPO / OUTPUT_DIRS[0]) == _tree(REPO / OUTPUT_DIRS[1])
    assert _tree(REPO / OUTPUT_DIRS[2]) == _tree(REPO / OUTPUT_DIRS[3])
    assert sorted(_tree(REPO / OUTPUT_DIRS[0])) == sorted(
        os.path.normpath(f"v1/{n}") for n in ("blockers.json", "manifest.json")
    )
    assert mif.main(["--check"]) == 0


def test_index_validates_and_cells_expected():
    index_dir = FIXTURE_ZONES / "index"
    zones = _read(index_dir / "zones.json")
    assert schema.validate_index(zones) == []
    assert zones["schema_version"] == 1 and zones["cell_zoom"] == 16
    assert [z["id"] for z in zones["zones"]] == IDS
    by_id = {z["id"]: z for z in zones["zones"]}
    for zone_id, z in by_id.items():
        assert z["version"] == 1
        assert z["manifest"] == f"{zone_id}/v1/manifest.json"
        assert (FIXTURE_ZONES / z["manifest"]).is_file() and (CONTENT_ZONES / z["manifest"]).is_file()
    assert by_id[ZONE_001]["kind"] == "exterior" and by_id[ZONE_002]["kind"] == "exterior"
    assert by_id[ZONE_001_IN]["kind"] == "interior"
    cell_files = sorted(p.name for p in (index_dir / "cells").iterdir())
    assert cell_files == sorted(EXPECTED_CELLS)
    for name, want in EXPECTED_CELLS.items():
        cell = _read(index_dir / "cells" / name)
        assert schema.validate_index(cell) == []
        assert (cell["z"], cell["x"], cell["y"]) == tuple(int(t) for t in name[:-5].split("_"))
        assert zi.cell_name(cell["z"], cell["x"], cell["y"]) == name
        assert [z["id"] for z in cell["zones"]] == want, name
        for ref in cell["zones"]:
            assert by_id[ref["id"]]["version"] == ref["version"]
    # the design §2 3x3 around the level origin's cell covers every cell file
    ox, oy = zi.lonlat_to_tile(126.9230, 37.5600)
    assert (ox, oy) == (55873, 25380)
    for name in EXPECTED_CELLS:
        _, x, y = (int(t) for t in name[:-5].split("_"))
        assert abs(x - ox) <= 1 and abs(y - oy) <= 1, name


def test_zone_002_is_200_m_east_in_next_cell():
    lat1, lon1, h1 = _origin(ZONE_001)
    lat2, lon2, h2 = _origin(ZONE_002)
    assert (lat1, lon1) == (37.5620, 126.9250) and h2 == h1
    east, north, up = transform.lonlat_to_enu(lon2, lat2, h2, (lat1, lon1, h1))
    assert abs(east - 200.0) <= 0.5 and abs(north) <= 0.5 and abs(up) <= 0.5
    assert zi.lonlat_to_tile(lon1, lat1) == (55873, 25379)
    x2, y2 = zi.lonlat_to_tile(lon2, lat2)
    assert x2 == 55874 != 55873 and y2 == 25379
    assert not _footprint(ZONE_001).intersects(_footprint(ZONE_002))
    assert not _footprint(ZONE_001_IN).intersects(_footprint(ZONE_002))
    for zones_root in (FIXTURE_ZONES, CONTENT_ZONES):
        path = zones_root / ZONE_002 / "v1" / zm.MANIFEST_NAME
        d = zm.load(path)
        assert schema.validate(d) == []
        rep = zm.check(d, path)
        assert rep.errors == []
        assert d["zone_id"] == ZONE_002 and d["kind"] == "exterior" and d["priority"] == 10
        assert d.get("portals", []) == []
        assert (zones_root / ZONE_002 / "v1" / "blockers.json").is_file()
    assert np.isfinite(_read(FIXTURE_ZONES / ZONE_002 / "v1" / zm.MANIFEST_NAME)["transform"]).all()


def test_cli_index_build_strict_from_fixture_root(tmp_path):
    out = tmp_path / "index"
    argv = ["index", "build", "--zones-root", str(FIXTURE_ZONES), "--out", str(out), "--strict"]
    assert (FIXTURE_ZONES / "index" / "zones.json").is_file()  # the root holds index/: scan_zones skips it
    assert zone_main(argv) == 0
    assert _tree(out) == _tree(FIXTURE_ZONES / "index")
